### ISSUE TITLE
Desired fields but not supported

### ISSUE THREAD

**Issue by YanchunHe** [NorwegianClimateCentre/noresm2cmor#110]
## Desired fields but not supported
Because fields are **NOT AVAILABLE** in the model output, or the formulation is **UNCLEAR**, or quite some work to do to add support to very few fields so that it is not done yet, see the comments on the _Notes_ column (you need to scroll right to see it)

If you find these fields are critically important and are available in the model output,  please comment under this issue, and update the corresponding entries in the [google data request sheet](https://docs.google.com/spreadsheets/d/1-XOmrpOewOJ4msZ2cuQ41NRiMKgMZ5BfiNeAAFUsp3M/edit#gid=1501063989)

---

6hrLev | 6hrPt | aerosol | ec550aer | EC550AER/DAYFOC | YH:not available,DAYFOC
-- | -- | -- | -- | -- | --
6hrPlevPt | 6hr | land | mrsol | SOILLIQ+SOILICE | YH:not available
6hrPlevPt | 6hr | land | mrsos | SOILWATER_10CM | YH:not available
6hrPlevPt | 6hr | land | tsl | TSL | YH:not available
CFday | day | atmos | rsdt | FSNTOA+FSUTOA | YH: not available
CFday | day | atmos | rsut | FSUTOA | YH: not available
E3hrPt | 3hrPt | atmos | aerasymbnd | planned (AERASYBNDi, where i=1-14) | YH: CONFIRM
E3hrPt | 3hrPt | atmos | aeroptbnd | planned (AERTAUBNDi, where i=1-14) | YH: CONFIRM
E3hrPt | 3hrPt | atmos | aerssabnd | planned (AERSSABNDi, where i=1-14) | YH: CONFIRM
E3hrPt | 3hrPt | atmos | albdiffbnd | ASDIF (0.2-0.7 um) and ALDIF (0.7-5 um) | YH:UNCLEAR
E3hrPt | 3hrPt | atmos | albdirbnd | ASDIR (0.2-0.7 um) and ALDIR (0.7-5 um) | YH:UNCLEAR
Eday | day | land | albsn | SNOFSRVD+SNOFSRVI+SNOFSRND+SNOFSRNI)/(SNOFSDSVD+SNOFSDSVI+SNOFSDSND+SNOFSDSNI | YH:todo
Eday | day | land | cnc | PCT_LANDUNIT & PCT_NAT_PFT | YH:todo; YF, see vegFrac
Eday | day | land | cw | H2OCAN | YH:unit conversion from mm to kg m-2 needed
Eday | day | land | mrtws | TWS | YH:unit conversion from mm to kg m-2 needed
Eday | day | land | sw | H2OSFC, VOLR | YH: todo, 20191029;YF, different units, H2OSFC is only for land surface water (mm), VOLR is for river channel water storage (m3)
Emon | mon | atmos | sfcWindmax | n/a | YH: changed to n/a.; OL: Added formula.
Emon | mon | land | fNLitterSoil | LITR1N_TO_SOIL1N+LITR2N_TO_SOIL1N+LITR2N_TO_SOIL2N+LITR3N_TO_SOIL2N+LITR3N_TO_SOIL3N | YH:not available
Emon | mon | land | fNVegLitter | LEAFN_TO_LITTER+FROOTN_TO_LITTER | YH:not available
Emon | mon | land | fProductDecomp | PRODUCT_CLOSS | YH:not available
EmonZ | mon | ocean | sltbasin | msflx |  
ImonAnt | mon | landIce | mrroLi | QRUNOFF_ICE |  
ImonGre | mon | landIce | mrroLi | QRUNOFF_ICE |  
Lmon | mon | land | baresoilFrac | PCT_LANDUNIT(0, :, :)*PCT_NAT_PFT(0, : ,:) | YF, baresoilFrac = PCT_LANDUNIT(0, :, :)*PCT_NAT_PFT(0, : ,:), 1st item of PCT_LANDUNIT is for natural vegetated landunit and first item of PCT_NAT_PFT is baresoil
Lmon | mon | land | burntFractionAll | FAREA_BURNED |  
Lmon | mon | land | cropFrac | PCT_LANDUNIT(1, :, :), PCT_CFT | YF, cropFrac = PCT_LANDUNIT(1, :, :), item 1 of PCT_LANDUNIT is for crop landunit; PCT_CFT tells the fractions of each specific 64 crop types
Lmon | mon | land | fLitterSoil | LITR1C_TO_SOIL1C+LITR2C_TO_SOIL1C+LITR2C_TO_SOIL2C+LITR3C_TO_SOIL2C+LITR3C_TO_SOIL3C |  
Lmon | mon | land | treeFrac | PCT_LANDUNIT(0, :, :)*PCT_NAT_PFT(1:8, : ,:) | YF,index 1-8 are for trees
Oclim | monC | ocean | diftrblo | difintlvl;difint |  
Oclim | monC | ocean | diftrelo | difisolvl;difiso |  
Oclim | monC | ocean | difvho | difdialvl;difdia |  
Oclim | monC | ocean | difvso | difdialvl;difdia |  
Oclim | monC | ocean | zfullo | dz, sealv | MB,for layer vertical coordinate, create monthly climatology from monthly zfullo
Oclim | monC | ocean | zhalfo | dz, sealv | MB, for layer vertical coordinate, create monthly climatology from monthly zhalfo
Ofx | fx | ocean | masscello | pdepth, depth_bnds, pbot, pdepth | MB, for level vertical coordinate, g = 9.806 m s-2, masscello(:,:,k) = (min(pdepth(:,:),depth_bnds(2,k))-min(pdepth(:,:),depth_bnds(1,k)))*pbot(:,:)/(pdepth(:,:)*g)
Omon | mon | ocean | htovgyre |   | MB, can maybe be obtained offline (see Griffies et al., 2016)
Omon | mon | ocean | htovovrt |   | MB, can maybe be obtained offline (see Griffies et al., 2016)
Omon | mon | ocnBgchem | fsfe | dust input file | YH:UNCLEAR
Omon | mon | ocnBgchem | fsn | ndep input file | YH:UNCLEAR
Omon | mon | ocnBgchem | intdic | vint(dissiclvl*12/1000) | YH:not available
Omon | mon | ocnBgchem | intdoc | vint(dissoclvl*122*12/1000) | YH:not available
Omon | mon | ocnBgchem | intpoc | vint(detoclvl*122*12/1000) | YH:not available
Oyr | yr | ocean | diftrblo | difintlvl | MB, yearly average of monthly difintlvl
Oyr | yr | ocean | diftrelo | difisolvl | MB, yearly average of monthly difisolvl
Oyr | yr | ocean | difvho | difdialvl | MB, yearly average of monthly difdialvl
Oyr | yr | ocean | difvso | difdialvl | MB, yearly average of monthly difdialvl
SImon | mon | seaIce | siareaacrossline | Extract from aicetranx and aicetrany | jbd
SImon | mon | seaIce | simassacrossline | Extract from simasstranx and simasstrany | jbd
day | day | atmos | uas | n/a |  
day | day | atmos | vas | n/a |  
day | day | landIce | snc | FSNO | YH:not available
day | day | landIce | snw | SNOWICE+SNOWLIQ | YH:not available

**Comment by JorgSchwinger** [comment]
The fields intdic, intdoc, and intpoc (while not being critically important) would be nice to have and the fields to calculate them (dissiclvl, dissoclvl, and detoclvl) are available in the output. Also I am pretty sure that a way to vertically integrate fields is already there, because in CMIP5 the variable intpp was calculated from pplvlv by vertical integration.

**Comment by IngoBethke** [comment]
sumz simply computes the vertical sum, if I recall correctly.

**Comment by YanchunHe** [comment]
> The fields intdic, intdoc, and intpoc (while not being critically important) would be nice to have and the fields to calculate them (dissiclvl, dissoclvl, and detoclvl) are available in the output. Also I am pretty sure that a way to vertically integrate fields is already there, because in CMIP5 the variable intpp was calculated from pplvlv by vertical integration.

fixed this.

**Comment by YanchunHe** [comment]
Hi Alf, please refer to #80

**Comment by YanchunHe** [comment]
> Dirk and I can't find the double radiation fields in the cmorized output, such as rlutaf, or more
> generally r*af. Are there any problems with these fields, Yanchun?

Hi Alf, please refer to #80

**Comment by YanchunHe** [comment]
The following additional fields are tested and supported based on 'piClim-spAer-anthro' experiment:
```
climodis_Emon
cltmodis_Emon
clwmodis_Emon
cod_AERday
cod_AERmon
emidust_AERmon
orog_Emon
pfull_AERmon
pfull_CFday
phalf_AERmon
phalf_CFday
reffclwtop_AERmon
```

Sample output:
- /scratch/yanchun/cmorout/NorESM2-LM/piClim-spAer-anthro/v20190815/
