### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - hist-nat (realisation 2)

### ISSUE THREAD

**Issue by DirkOlivie** [NorwegianClimateCentre/noresm2cmor#114]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS2345K/noresm/cases (N1850natonly_02_f19_tn14_20190909)
/projects/NS9560K/noresm/cases (NSSP245frc2natonly_02_f19_tn14_20191015)

**experiment_id**
hist-nat

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
N1850natonly_02_f19_tn14_20190909, 1850-2014
NSSP245frc2natonly_02_f19_tn14_20191015, 2015-2020

### Optional information

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 0421-01-01'

**branch_method**
'Hybrid-restart from year 1631-01-01 of piControl'

**other information**
realisation = 2
The full simulation consists of two experiments.  The time counting in the files is different between the first and the second experiment.  This is because the second period has started as a hybrid from the first period.
The period 1850-2014 : time:units = days since 1850-01-01 00:00:00
The period 2015-2020 : time:units = days since 2015-01-01 00:00:00

**Comment by YanchunHe** [comment]
CMORized and ready to publish

**data path**
- /tos-project1/NS9034K/CMIP6/DAMIP/NCC/NorESM2-LM/hist-nat/r2i1p1f1

**version**
- v20190920

**sha256sum**
- .r2i1p1f1.sha256sum_v20190920

**Comment by monsieuralok** [comment]
@DirkOlivie @YanchunHe published

**Comment by YanchunHe** [comment]
cmorized with addtional fields

**data path**
- /tos-project1/NS9034K/CMIP6/DAMIP/NCC/NorESM2-LM/hist-nat/r2i1p1f1

**version**
- v20191108

**sha256sum**
- .r2i1p1f1.sha256sum_v20191108b

**Comment by YanchunHe** [comment]
Transfer of files from dedicated post-processing node to NIRD project area is not finished yet (uncomplete), should pause the publishing.

**Comment by YanchunHe** [comment]
Now the files are complete and ready to republish

**data path**
- /tos-project1/NS9034K/CMIP6/DAMIP/NCC/NorESM2-LM/hist-nat/r2i1p1f1

**version**
- v20191108

**sha256sum**
- .r2i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@DirkOlivie @YanchunHe published
