### ISSUE TITLE
Availability of model output

### ISSUE THREAD

**Issue by YanchunHe** [NorwegianClimateCentre/noresm2cmor#116]
As far as I can tell, there are several options to toggle on model output:

- -DAEROCOM
- -DAEROFFL
- COSP set-up
- fincl-namelist option
- f_CMIP='mdxxx'
- f_CMIP='mxxxx'
- f_apeff_ai='mxxxx'
- f_apond_ai=='mxxxx'
- f_ardg='mxxxx'
- -DAEROFFL
- -DRFMIPIRF
- history_aerosol=.true.
- set HAMOCC_CFC=TRUE in env_build.xml
- set HAMOCC_CISO=TRUE in env_build.xml
- set HAMOCC_NATTRC=TRUE in env_build.xml

Could you specify more sample output for those options if you want to support these output?

One example:

**CaseName:NHIST_spAer_f19_tn14_20190925**
availability: history_aeroso=.true.,
activity: RFMIP
expid: hist-spAer-all
location: /projects/NS9560K/noresm/cases/NHIST_spAer_f19_tn14_20190925

If you have ideas, please post under this issue.

**Comment by Kirkevag** [comment]
Copied from #80:

I can confirm that history_aerosol=.true. is used in all my RFMIP simulations (on ns9560k), of which 
3 also have the COSP simulator activated:

NHIST_spAer_f19_tn14_20190925
piClim-lu2deg                                         + COSP
piClim-SpAer2014                                  + COSP
piClim-SpAer-anthro                              + COSP

Others can best answer for their own simulations, or you can perhaps check by

ncdump -h "simulation example h0 file" | grep MODIS

whether you get any hits. Does this help?

I don't have overview of the other simulations, but I'm quite confident that history_aerosol is true for all RFMIP and AerChemMIP simulations. Isn't this marked off in any of the google sheets?

**Comment by YanchunHe** [comment]
OK, thanks Alf.

Ideally, it is the best if one experiments has all output activated, as I suggested in the begging.

But at least now, I know history_aerosol=.true, COSP.
(and one more experiment with certain CFmon fields).

Google sheet indicates the option to activate it.

I can't invest more time to look through every simulation.

**Comment by YanchunHe** [comment]
@DirkOlivie

**Comment by JorgSchwinger** [comment]
- set HAMOCC_CFC=TRUE in env_build.xml
- set HAMOCC_NATTRC=TRUE in env_build.xml

These are set in the historical and OMIP. They will not be used in other experiments. The natural tracers have been cmorized already, and I think the CFCs have been fixed in a new version (but not yet officially cmorized).

- set HAMOCC_CISO=TRUE in env_build.xml

This option will not be used in CMIP6 with the current model version.

**Comment by YanchunHe** [comment]
> * set HAMOCC_CFC=TRUE in env_build.xml
> * set HAMOCC_NATTRC=TRUE in env_build.xml
> 
> These are set in the historical and OMIP. They will not be used in other experiments. The natural tracers have been cmorized already, and I think the CFCs have been fixed in a new version (but not yet officially cmorized).
> 
> * set HAMOCC_CISO=TRUE in env_build.xml
> 
> This option will not be used in CMIP6 with the current model version.

Thanks Jörg! I used historical run for the test, so the available model output are included.
