### ISSUE TITLE
subroutine to interpolate from sigma to pressure level

### ISSUE THREAD

**Issue by YanchunHe** [NorwegianClimateCentre/noresm2cmor#120]
Hi Ingo,  I notice that an external fortran subroutine  vinth2pecmwf is called to interpolate data from hybrid sigma to pressure levels,

e.g., in m_modelsatm.F, (line 3044-3045, commit 49ba32d)
```fortran
          CALL vinth2pecmwf(ifld,ofld,hyam,hybm,p0_hpa,tmp1d,plevs_hpa,
     .    1,ps,missing,1,idm,jdm,ldm,ldm,pdm,0,tbot,phis)
```
ldm,ldm are passed are passed to NLEVI, NLEVIP1.

But should we pass ldm, ldm+1 since NLEVIP1=NLEVI+1, if I understand correctly. Thanks!

**Comment by IngoBethke** [comment]
I just had a look at the code and NLEVIP1 is only used in declaring the three variables  
HBCOFA(NLEVIP1),HBCOFB(NLEVIP1),PLEVI(NLEVIP1)

I couldn't see that these variables are accessed anywhere at NLEVI+1. Also, Hyam and hybm have dimensions ldm. 

Note that 
C****        HBCOFA  - 2 DIMENSIONAL ARRAY CONTAINING "A" OR PRESSURE
C****                  COEFICIENTS FOR COMPUTING PRESSURE AT A LEVEL.
C****                  ARRAY IS 2XNLEVIP1.  THE 1ST INDEX TAKES ON
C****                  THE VALUE OF EITHER
C****                   1 - FOR LEVEL INTERFACES (OR 1/2 LEVELS) OR;
C****                   2 - FOR LEVEL MIDPOINTS  (OR FULL LEVELS WHERE
C****                       VIRTUALLY ALL VARIABLES ARE LOCATED)

I think it is because we use 2 that I choose to specify ldm instead of ldm+1. I do think I have tested with bounds check and did not get any error. The verification I performed some 8 years ago looked fine as well. 

If you think it is worth you can test with specifying hybrid coefficients at interface levels and then verify the result.

**Comment by YanchunHe** [comment]
Thanks Ingo! I will try.

**Comment by YanchunHe** [comment]
In addition, I found phis and tbot are allocated and read from model output only if processing 'Z3' and 'T'. But the phis and tbot are required for the `interp_z` for all fields on 'plev'.
```fortran
2327       lreqphis=.FALSE.
2328       IF (TRIM(ivnm1).EQ.'Z3'.OR.TRIM(ivnm1).EQ.'T') THEN
2329         lreqphis=.TRUE.
2330         IF (.NOT.ALLOCATED(phis)) THEN
2331           ALLOCATE(phis(idm,jdm),tbot(idm,jdm),STAT=status)
2332           IF (status.NE.0) STOP 'cannot allocate enough memory'
2333         ENDIF
2334       ENDIF
```

```fortran
        IF (TRIM(ivnm).EQ.'T') THEN  
          CALL vinth2pecmwf(ifld,ofld,hyam,hybm,p0_hpa,tmp1d,plevs_hpa,
     .    1,ps,missing,1,idm,jdm,ldm,ldm,pdm,1,tbot,phis)
        ELSEIF (TRIM(ivnm).EQ.'Z3') THEN  
          CALL vinth2pecmwf(ifld,ofld,hyam,hybm,p0_hpa,tmp1d,plevs_hpa,
     .    1,ps,missing,1,idm,jdm,ldm,ldm,pdm,-1,tbot,phis)
        ELSE 
          CALL vinth2pecmwf(ifld,ofld,hyam,hybm,p0_hpa,tmp1d,plevs_hpa,
     .    1,ps,missing,1,idm,jdm,ldm,ldm,pdm,0,tbot,phis)
        ENDIF 
```

How can I understand this? or is this a bug?

**Comment by YanchunHe** [comment]
And I guess you have modified the original version of subroutine VINTH2PECMWF (if it is from somewhere) . Since in its head information, the HBCOFA is 2xNLEVIP1 (2D) for midpoints and interfaces cases.

But this is OK, since we can call this subroutine with different arguments when processing midpoints and interfaces fields. I will see if I need some modification so that it is compatible with the both situations.

**Comment by IngoBethke** [comment]
In CMIP5, the only fields we interpolated were T, Z, Q, U and V. To my understanding, phis and tbot are only required if extrapolation into the ground is performed, which doesn't make much sense for Q, U and V. 

In case phis and tbot are unset but actually used in the interpolation then it qualifies indeed as a bug but I would expect this to be visible in the result.

**Comment by YanchunHe** [comment]
Thanks! I see the differences now. And will also only keep extrapolation for T and Z, so `vinth2pecmwf` works well if tbot and phis are not presented.

**Comment by IngoBethke** [comment]
Note that the fields are set to zero if no extrapolation is performed. This is reasonable for Q, U and V but I don't know about other quantities. Maybe @lisesg has some input.

I suspect that many users who compute zonal means from pressure level data are too lazy to worry about masking orography. So either one should define the points below ground as missing (this would force the user to explicitly deal with orography) or specify something that has a minimal impact on the computation of zonal means (to specify 0 K for temperature or 0 m for geopotential height would have a severe impact).

**Comment by YanchunHe** [comment]
The EQ-flux related fields (epfy,epfz, etc) are set to missing (instead of zero) if their pressure level is below the model lowest pressure level and no extrapolation is performed.

I have no idea how one do the zonal mean inside the model.

**Comment by lisesg** [comment]
For epfy etc, how to handle points where the pressure surfaces intersect topography is described in the DynVarMip paper (Gerber and Manzini, 2016): "We recommend that modeling centers either (1) extrapolate the required variables below the surface before computing the diagnostics (see, for example, Trenberth et al., 1993) or (2) take a representative average over all longitudes that are still above the surface. With the second option, a zonal average should be marked missing only if the pressure level is below the surface at more than half of all longitudes. Likewise, a time average should be take over time steps for which the data are available, and only marked missing if more than half the data are missing."

I don't know if there are corresponding recommendations for other fields like T or Z though.

The zonally-averaged fields that epfy etc are derived from (VTHzm, Uzm, etc) are computed during the model run following something that is similar to the second option, but I think the threshold for setting a point in to zero is that values are missing for a third of the longitudes (and not half like in Gerber and Manzini). This is done in the ctem.F90 file, which is used when the CAM namlist option do_circulation_diags is set to true.

**Comment by YanchunHe** [comment]
Thanks Lise and Ingo, I think this issue is clear now and can be closed.
