### ISSUE TITLE
How to present core dump when program crashes?

### ISSUE THREAD

**Issue by YanchunHe** [NorwegianClimateCentre/noresm2cmor#132]
Hi Ingo, is there a way to prevent core dump when noresm2cmor tool crash (may due to no obvious reason). the core dumps are huge and may exceed my home disk quota.

As I see, -g is not used in the makefile, and the core dump gives no useful information.

Thanks! 

An exmaple of the dumped cores are:

yanchun@ipcc:/scratch/NS9034K/noresm2cmor/bin
$ ll
total 293G
-rw------- 1 yanchun ns9034k 3.4M Nov 16 16:42 core.229252
-rw------- 1 yanchun ns9034k  18G Nov 16 15:45 core.229670
-rw------- 1 yanchun ns9034k  19G Nov 16 15:48 core.230093
-rw------- 1 yanchun ns9034k  18G Nov 16 15:47 core.230521
-rw------- 1 yanchun ns9034k  42G Nov 16 16:50 core.230948
-rw------- 1 yanchun ns9034k  17G Nov 16 15:47 core.231375
-rw------- 1 yanchun ns9034k  18G Nov 16 15:47 core.231802
-rw------- 1 yanchun ns9034k  17G Nov 16 15:46 core.232269
-rw------- 1 yanchun ns9034k  17G Nov 16 15:46 core.233329
-rw------- 1 yanchun ns9034k  40G Nov 16 16:50 core.234377
-rw------- 1 yanchun ns9034k  16G Nov 16 15:48 core.235122
-rw------- 1 yanchun ns9034k  16G Nov 16 15:48 core.235563
-rw------- 1 yanchun ns9034k  16G Nov 16 15:48 core.236004
-rw------- 1 yanchun ns9034k  21G Nov 16 16:48 core.260778
-rw------- 1 yanchun ns9034k  21G Nov 16 16:50 core.267433
-rw------- 1 yanchun ns9034k  11G Nov 16 16:44 core.275205
-rw------- 1 yanchun ns9034k 6.5G Nov 16 16:45 core.283204

**Comment by IngoBethke** [comment]
check system defaults with
ulimit -a

you should be able to set core size limit to 0 with 
ulimit -c 0

**Comment by YanchunHe** [comment]
thanks!
