### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - lig127k

### ISSUE THREAD

**Issue by ChunchengGuo** [NorwegianClimateCentre/noresm2cmor#159]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS4659K/chuncheng/cases_zhongshi/

**experiment_id**
lig127k

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
LIG127k, 2101-2200

### Optional information

**parent_experiment_id**
no parent

**parent_experiment_rip**
'no parent'

**parent_time_units**
'no parent'

**branch_method**
none

**other information**

**Comment by YanchunHe** [comment]
cmorized

**data path**
- /tos-project1/NS9034K/CMIP6/PMIP/NCC/NorESM2-LM/lig127k/r1i1p1f1

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108

**Comment by monsieuralok** [comment]
@ChunchengGuo @YanchunHe published

**Comment by YanchunHe** [comment]
pr is cmorized:

/tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-LM/lig127k/v20191108c

**Comment by ChunchengGuo** [comment]
@YanchunHe 
it looks good; thanks, and could you ask @monsieuralok to publish it?

**Comment by monsieuralok** [comment]
@ChunchengGuo @YanchunHe published
