### ISSUE TITLE
 sys_CMIP6_default.nml, create_CMIP6_sha256sum.sh and create_CMIP6_links.sh need to be adapted to new folder structure

### ISSUE THREAD

**Issue by IngoBethke** [NorwegianClimateCentre/noresm2cmor#16]
I tidied up the /projects/NS9034K/CMIP6 folder structure so that the regular users only see what they need to see. The changes require modification of the files mentioned in the subject. The changes are following

I renamed /projects/NS9034K/CMIP6/cmorout to /projects/NS9034K/CMIP6/.cmorout to hide this folder (also hid the “test” folder). 

I temporarily placed a symlink “cmorout” that points to “.cmorout" in order to avoid disruption of CMOR-ization and ESGF download. But if cmor-izing new data please use .cmorout. Eventually I will delete the symlink “cmorout”. 

I’ve update all existing symlinks to use .cmorout. I didn’t try to modify your create_CMIP6_links.sh because that one looked outdated to me. Most importantly, if creating new symlinks please use .cmorout instead of cmorout.  

Next, I’ve added a “.” at the beginning of the file names of all r*i*p*f*.sha256sum and r*i*p*f*.map files to hide these files. When generating new sha256sum-files please use the name format .r*i*p*f*.sha256sum instead of r*i*p*f*.sha256sum. 

I also deleted all .sha256sum files which I assumed were temporary files. It would be great if these could be deleted automatically in the future.

**Comment by IngoBethke** [comment]
To make it easier for local users I've added symlinks "latest" that always point to the latest version (this was the standard procedure for CMIP5). For that purpose, I added a script create_CMIP6_links_latest.sh to the scripts folder. In the future, it would be good if "latest" links could already be created/update with the create_CMIP6_latest.sh script.

**Comment by YanchunHe** [comment]
A broken link v20190815 was created under data folder. Need to be removed some point (todo).

**Comment by YanchunHe** [comment]
Removed:
`rm -f /projects/NS9034K/CMIP6/*/NCC/NorESM2-LM/*/r1i1p1f1/*/*/g?/v20190815/v20190815`

**Comment by YanchunHe** [comment]
fixed in commit 417ec63d11a7edcab62fad40c6bea813648194b3
