### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - midHolocene

### ISSUE THREAD

**Issue by ChunchengGuo** [NorwegianClimateCentre/noresm2cmor#161]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS4659K/chuncheng/cases_zhongshi/

experiment_id
midHolocene

model_id
NorESM2-LM

CASENAME(s) and years to be CMORized
MH6000y, 2101-2200

Optional information
parent_experiment_id
no parent

parent_experiment_rip
'no parent'

parent_time_units
'no parent'

branch_method
none

other information

**Comment by YanchunHe** [comment]
The last 10 years has fewer cmorized fields than others, otherwise, all looks fine.

There is no error report for the last 10 years during cmorziation. 

Otherwise, it is ready to be published?

Can you check? @ChunchengGuo

**Comment by YanchunHe** [comment]
yyyy1	yyyy2	number of files
2101	2110	448
2111	2120	448
2121	2130	448
2131	2140	448
2141	2150	448
2151	2160	448
2161	2170	448
2171	2180	448
2181	2190	448
2191	2200	321

**Comment by YanchunHe** [comment]
cmorized

**data path**
- /tos-project1/NS9034K/CMIP6/PMIP/NCC/NorESM2-LM/midHolocene

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108

**Comment by ChunchengGuo** [comment]
@YanchunHe 
thanks! I just had a quick look, it seems that 'pr' from Amon is missing in the output. Would you have a quick look if possible, since this is an important variable. 'pr' is also missing in the lig127k experiment as well.

**Comment by YanchunHe** [comment]
There is no PRECT in monthly files during this perid:
 for example in :

/projects/NS4659K/chuncheng/cases_zhongshi/MH6000y/atm/hist/MH6000y.cam.h0.2191-01.nc

can you check that?

**Comment by ChunchengGuo** [comment]
yes, that was indeed missing..
is there a way to do calculation such as "PRECT=PRECC+PRECL+PRECSC+PRECSL"?
if it is not a quick fix, just ignore it and move ahead with publishing.

Thanks!

**Comment by YanchunHe** [comment]
I can do that later.

**Comment by YanchunHe** [comment]
Please publish the above mentioned data @monsieuralok

**Comment by monsieuralok** [comment]
@ChunchengGuo @YanchunHe published

**Comment by YanchunHe** [comment]
todo: add pr for the last period (also for lig127k).

**Comment by YanchunHe** [comment]
pr for the last 10 years is cmorized:

/tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-LM/midHolocene/v20191108c/pr_Amon_NorESM2-LM_midHolocene_r1i1p1f1_gn_219101-220012.nc

does this look correct? @ChunchengGuo

**Comment by ChunchengGuo** [comment]
@YanchunHe 
yes, it looks good, thanks!
Could you do the other 190 years as well?

**Comment by YanchunHe** [comment]
There are pr for the first 190 years., right?

**Comment by ChunchengGuo** [comment]
no.. there is only last 10 years in the folder..

**Comment by YanchunHe** [comment]
the others should be found under v20191108 folder.

**Comment by ChunchengGuo** [comment]
no, I checked - not there..

**Comment by YanchunHe** [comment]
ok, I will do this later.

**Comment by YanchunHe** [comment]
addeded pr for all years, and ready to be published.

**data path**
- /tos-project1/NS9034K/CMIP6/PMIP/NCC/NorESM2-LM/midHolocene/
- /tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-LM/midHolocene/v20191108c

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108c

**Comment by monsieuralok** [comment]
@ChunchengGuo @YanchunHe published
