### ISSUE TITLE
question about the NorESM file naming on ESGF

### ISSUE THREAD

**Issue by YanchunHe** [NorwegianClimateCentre/noresm2cmor#17]
(by Jan Griesfeller)

I just downloaded some AOD data from ESGF (var name od550aer) of  some models including NorESM and noted a slight difference in the naming scheme. The files are also on NIRD in the /nird/projects/NS9252K/CMIP6/raw/ directory.

It seems we use different naming scheme:
NorESM:
od550aer_AERmon_historical_NorESM2-LM_r1i1p1f1_gn_185001-185912.nc
all other models:
od550aer_AERmon_CESM2-WACCM_historical_r1i1p1f1_gn_185001-201412.nc

The difference is that the other models put the experiment_id
after the model name while we have it the other way round.

I just wonder if we did something wrong or not, but since I am supposed to write a converter to the aerocom naming scheme, this difference causes some additional work.

Any opinions on that?

**Comment by YanchunHe** [comment]
The part of source code (some related .json files) that defines the CMOR file from our CMOR tool:
`
'output_file_template'     '<variable_id><table><experiment_id><source_id><variant_label><grid_label>'
`
is slightly different from the template provided by CMOR: 
`
"output_file_template":    "<variable_id><table><source_id><experiment_id><_member_id><grid_label>"
`

That is, the order of source_id and experiment_id is reversed.

The already-published data will be renamed, and corresponding links/map files will be updated. Data will be republished to ESGF.

File name format will follow the CMOR template in the future CMORization processes.

**Comment by IngoBethke** [comment]
It must be a bug in the Fortran version of the CMOR library. The CMIP6 drs document https://www.earthsystemcog.org/site_media/projects/wip/CMIP6_global_attributes_filenames_CVs_v6.2.6.pdf is supports Jan's naming. E.g. Example when there is no sub-experiment: tas_Amon_GFDL-CM4_historical_r1i1p1f1_gn_196001-199912.nc

**Comment by IngoBethke** [comment]
Ah, I read now your latest emails, Yanchun. You are right, the bug was in the definition of output_file _template. I fixed it and pushed the change.

**Comment by YanchunHe** [comment]
fixed by commits: 0cf3c5078d365f918368619c8e4a39daf39c6d65 and dcb603100346527ae2bc457733e4c3b15b34961b
