### ISSUE TITLE
cross-reference among source, source_id, model_id

### ISSUE THREAD

**Issue by YanchunHe** [NorwegianClimateCentre/noresm2cmor#29]
model_id in cmip5 is replaced with source_id in CMIP6
in current implementation, model_id is kept in mod_*.nml, but not used. And source_id is replaced with source.

in mod_*.nml
```
 2  model_id      = 'NorESM2-LM',
  3  source        = 'NorESM2-LM (2017): ....'
```
in m_namelist.F
```
963       CALL merge_strarr(slenmax,smax,source,source1,linebreaks)
1583       CALL json%add(p,'source_id',TRIM(source1))
1584       CALL json%add(p,'source',TRIM(source1))
```
maybe it is a typo?

Change
`CALL json%add(p,'source_id',TRIM(source1))`
 to
`CALL json%add(p,'source_id',TRIM(model_id))`
If this is not intended?

**Comment by IngoBethke** [comment]
Sounds reasonable. Though, it would be good if you could perform a quick test before pushing the change. Thanks.

**Comment by YanchunHe** [comment]
Yes, it tested it and it works, if I put values in CMIP6_CV.json to 'source', without warning.

I will commit the change. It will not affect previous cmorization namelist.

However, if I change the
```
institution   = 'NorESM Climate modeling Consortium consisting of CICERO (Center for International Climate and Environmental Research, Oslo 0349), MET-Norway (Norwegian Meteorological Institute, Oslo 0313), NERSC (Nansen Environmental and Remote Sensing Center, Bergen 5006), NILU (Norwegian Institute for Air Research, Kjeller 2027), UiB (University of Bergen, Bergen 5007), UiO (University of Oslo, Oslo 0313) and UNI (Uni Research, Bergen 5008), Norway. Mailing address: NCC, c/o MET-Norway, Henrik Mohns plass 1, Oslo 0313, Norway',
```
copied from the CMIP6_CV.json
It will have warning like:
! Warning: Your input attribute institution "NorESM Climate modeling Consortium consisting of CICERO (Center for International Climate and Environmental Research, Oslo 0349), MET-Norway (Norwegian Meteorological Institute, Oslo 0313), NERSC (Nansen Environmental and Remote Sensing Center, Bergen 5006), NILU (Norwegian Institute for Air Research, Kjeller 2027), UiB (University of Bergen, Bergen 5007), UiO (University of Oslo, Oslo 0313) and UNI (Uni Research, Bergen 5008), Norway. Mailing address: NCC, c/o MET-Norway, Henrik Mohns plass 1," will be replaced with
! "NorESM Climate modeling Consortium consisting of CICERO (Center for International Climate and Environmental Research, Oslo 0349), MET-Norway (Norwegian Meteorological Institute, Oslo 0313), NERSC (Nansen Environmental and Remote Sensing Center, Bergen 5006), NILU (Norwegian Institute for Air Research, Kjeller 2027), UiB (University of Bergen, Bergen 5007), UiO (University of Oslo, Oslo 0313) and UNI (Uni Research, Bergen 5008), Norway. Mailing add

(Note there are truncation of string in the end, but that should be related to the write(*,*) statement).

I guess the the institution have quite some special characters, and fortran does not value them as the same string, anyhow (I don't know why).

**Comment by IngoBethke** [comment]
The string is exactly of length 500 characters at ",". So if you increase the maximum length from 500 to e.g. 1024 then it should work.

**Comment by IngoBethke** [comment]
The removal of "source" from the model input namelist caused all my active CMOR-ization processes to crash after re-compilation since I did not modify all input namelists. Also, it will break CMIP5 cmor-ization backward compatibility. Therefore it would be good if the source, source1 lines could be added back in m_namelists.F. Thanks.

**Comment by YanchunHe** [comment]
I did not touch source, but only set source_id with model_id instead of using source1.

Please pull again to my last push, and then you can change as it is backward compatible.

**Comment by IngoBethke** [comment]
Sorry, I was mistaken then. The reason for the crash must be of different nature.

**Comment by IngoBethke** [comment]
It was this change that caused my CMOR-ization to crash https://github.com/NorwegianClimateCentre/noresm2cmor/commit/943dcc4b493c776d3ad4ba184d2268246c270e09#diff-549f710a48116db7c44533ecedb5a864

I am going to move the source_type specification for NorCPM1 from model to experiment namelist.
