### ISSUE TITLE
create_CMIP6_sha256sum.sh broken for use on multiple realisation

### ISSUE THREAD

**Issue by IngoBethke** [NorwegianClimateCentre/noresm2cmor#34]
I received the following error:

+ folder=/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/piControl
+ cd /projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/piControl
+ reals=($(basename $(find -maxdepth 1  -type d -name 'r*' -print)))
+++ find -maxdepth 1 -type d -name 'r*' -print
++ basename ./r2i1p1f1 ./r1i1p1f1 ./r3i1p1f1
basename: extra operand ‘./r3i1p1f1’
Try 'basename --help' for more information.

There is something wrong in the line "reals = ...". The basename command typically only takes one main argument.

**Comment by YanchunHe** [comment]
Resolved. Now it supports multiple instances.
And it is also possible to provide arguments to the script.
see:
```
$ ./create_CMIP6_sha256sum.sh --help
Usage:
create_CMIP6_sha256sum.sh -e [path_to_experiment] -v [data_version] -O [TRUE]
	 Command line options:
	 -e, --exp=path_to_experiment                 :specify path to the data [optional];
	 -v, --version=vyyyymmdd                      :speicify variable version [optional];
	 -O, --overwrite=TRUE                         :specify if overwrite existed sha256sum file [optional];
```

commit: aee2f9ada907a9d66c1a76d7c97510285e5d6b29
