### ISSUE TITLE
updating local CMIP6_CV for NorESM1-F

### ISSUE THREAD

**Issue by ChunchengGuo** [NorwegianClimateCentre/noresm2cmor#45]
I 'source_id' registered NorESM1-F already at -

https://github.com/WCRP-CMIP/CMIP6_CVs/issues/786

And you could see it from the cmip6 cv here (search NorESM) -

https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html

Could someone help with updating the local CV? @IngoBethke may I 'poke' you? thanks

**Comment by IngoBethke** [comment]
Done in commit https://github.com/NorwegianClimateCentre/noresm2cmor/commit/77b439d827fad0ce8bf53d287f05f88e9239add6

@YanchunHe will need to pull the change.
