### ISSUE TITLE
[CMIP6 CMORization & ESGF-publication] lig127k - NorESM1-F

### ISSUE THREAD

**Issue by ChunchengGuo** [NorwegianClimateCentre/noresm2cmor#46]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS4659K/chuncheng/cases/

**experiment_id**
lig127k

**CASENAME(s) and years to be CMORized**
NBF1850OC_f19_tn11_01_127ka, 1501-1700

### Optional information
none

**parent_experiment_id**
no parent

**parent_experiment_rip**
r1i1p1

**parent_time_units**
no parent

**branch_method**
none

**other information**
Q: For the PI run with NorESM1-F, we have 1000 years spin-up + another 1000 years PIcontrol. This lig127k run was branched off from the PI spin-up (not PI control) at year 1000.  So I guess in this case lig127k has no parent, and the branch method should be none, rather than 'Hybrid-restart from year xxxx of piControl'?

**Comment by YanchunHe** [comment]
OK, according to CMIP6_CV.json, lig127k has 'no parent' experiment. Therefore, we can set all these here as 'no parent'.

But according to your description here, you should specify the information of parent experiment, i.e., piControl-spinup.

**Comment by ChunchengGuo** [comment]
I see from the already uploaded lig127 data by other groups also specify it as 'no parent', so guess that it is OK to proceed as it is. I have also no plan to upload any piControl-spinup data.

**Comment by YanchunHe** [comment]
lig127 by definition is 'no parent'
and you don't need to upload piControl-spinup, even for piControl

**Comment by YanchunHe** [comment]
### Ready to be published

**data  path**
- /projects/NS9034K/CMIP6/PMIP/NCC/NorESM1-F/lig127k/r1i1p1f1

**version**
- v20190920

**other information**
- PrePARE QC passed
- sha256sum calculated

**Comment by YanchunHe** [comment]
The following fields are excluded in cmorization for lig127k since they are not available in the piControl of NorESM1-F:

- sfdsi_Omon
- sidmassgrowthbot_SImon
- sidmassgrowthwat_SImon
- sidmassmeltbot_SImon
- sidmassmelttop_SImon

Namelist commits:
4c220e3
2972d90

**Comment by monsieuralok** [comment]
@ChunchengGuo @YanchunHe published

**Comment by YanchunHe** [comment]
CMORized with additional fields.

**data path**
- /tos-project1/NS9034K/CMIP6/PMIP/NCC/NorESM1-F/lig127k

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@ChunchengGuo @YanchunHe published
