### ISSUE TITLE
need to modify map-generation script to deal with duplicated entries in checksum files 

### ISSUE THREAD

**Issue by IngoBethke** [NorwegianClimateCentre/noresm2cmor#51]
I noticed that there are many sha256sum files with dubplicated entries (especially for PAMIP). If I understand correctly, this is caused by that the checksum script is appending to instead of overwriting existing checksum files (is that correct @YanchunHe ?). 

It is maybe not a problem to have duplicated entries in the checksum files but we should avoid dubplicated entries in the map files as these potentially can cause issues during publication. 

I suggest that @monsieuralok modifies his collect_maps_CMIP6.sh script and changes
cp -f "$MAPFILE" $FNAME
to 
cat "$MAPFILE" | sort -u > $FNAME
to deal with existing map files that contain dublicated entries.

I will try update the script create_CMIP6_maps.sh for the generation of new map files.

**Comment by YanchunHe** [comment]
That is right. I usually don't overwrite but append the sha256sum. I tried to remove the duplicated entries (kind of manually). But I may also update the script to automatically remove the existing entries.
But will be nice if create map script can also filter duplicated entries.

**Comment by IngoBethke** [comment]
I've modified the script for map-file generation to ignore duplicated entries in sha256sum files in commit
https://github.com/NorwegianClimateCentre/noresm2cmor/commit/39aebef5595fab32f704c298177fda1317135cfa
