### ISSUE TITLE
proposal for revised cmor-ization & ESGF-publication workflow

### ISSUE THREAD

**Issue by IngoBethke** [NorwegianClimateCentre/noresm2cmor#53]
@YanchunHe : why do we have separate issues for cmor-ization and ESGF publication request? Rarely someone wants only CMIP6 cmor-ization without publication. In my view, the current separation breaks the workflow and communication by introducing unnecessary complexity. The person who puts in the original request very likely wants to be notified when an experiment is published. Therefore I think it a bit unfortunate to close the original issue before that goal is reached and try to hand it over to a separate "publication queue". This, and the fact that we currently bundle multiple experiments in a single "publication queue" issue, makes it hard for the person who put in the original request to monitor the progress. @monsieuralok also mentioned that  he prefers to deal with the publication of one experiment at a time and not bundles of experiments. 

Considering the above, I recommend a revised workflow that combines cmor-ization and publication request in a single issue. This would mean that you are likely not the person who closes these issues but it would simplify the workflow and make it more robust. In the revised workflow, there is exactly one issue per experiment per model which deals with all aspects (e.g. if problems are found with the data then the issue can be re-opened until that data is retracted and replaced).

**Comment by IngoBethke** [comment]
I have added a new issue template "CMIP6 CMORization & ESGF-publication request" for NorESM data providers that want to CMORize and ESGF-publish a CMIP6 experiment. I also modified existing CMORization issues to include ESGF-publication. The old CMORization template is still available for the rare case that someone wishes to CMORize without publication.

The rational behind the new template is the following:

The data provider creates the issue and the person/team (currently @YanchunHe) who deals with the CMORization is automatically assigned. 

Once the CMOR-ization and QC is completed, a commented should be posted with a mention of the person/team (currently @monsieuralok) who deals with the ESGF-publication. 

The issues will be closed after successful ESGF publication and can be re-opened in case of retraction & data correction.

**Comment by IngoBethke** [comment]
Edited the contents above (Sunday 29. Sep)

**Comment by YanchunHe** [comment]
Thanks Ingo!

When I started to use the Issue to manage the workflow, some experiments have been cmorized, that is why I started to create Issues for only publishing data.

The ESGF publish request issue template will mostly be used by myself, and it is not straigthforward to be  added in the same template for the cmorization. And they are cross-referenced in the existing issues.

But I don't have particular preferences if we combine or split these two procedures. So will be happy if other users use the new tempate, but hopefully these different types of template will not cause confusion to them.

I think you can close this now. Thanks!




The reason why I used two templates are firstl

**Comment by IngoBethke** [comment]
Thanks for the clarification. We will see how it goes. We can still further adjust the workflow if necessary.
