### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - CMIP6 PAMIP pdSST-piArcSIC

### ISSUE THREAD

**Issue by lisesg** [NorwegianClimateCentre/noresm2cmor#55]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
Members 1-25:
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p5_pdSST-piArcSIC_mem1-25_f19_mg17_20190919
Members 26-50:
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p5_pdSST-piArcSIC_mem26-50_f19_mg17_20190919
Members 51-75:
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p5_pdSST-piArcSIC_mem51-75_f19_mg17_20190919
Members 76-100:
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p5_pdSST-piArcSIC_mem76-100_f19_mg17_20190919

**experiment_id**
pdSST-piArcSIC

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p5_pdSST-piArcSIC_mem1-25_f19_mg17_20190919: June 1st 2000 - May 31st 2001
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p5_pdSST-piArcSIC_mem26-50_f19_mg17_20190919: June 1st 2000 - May 31st 2001
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p5_pdSST-piArcSIC_mem51-75_f19_mg17_20190919: June 1st 2000 - May 31st 2001
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p5_pdSST-piArcSIC_mem76-100_f19_mg17_20190919: June 1st 2000 - May 31st 2001

### Optional information

**parent_experiment_id**
amip

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
days since 1975-01-01 00:00:00

**branch_method**
'Hybrid-restart from year 2000-04-01 of amip',

**other information**
The experiment is a hybrid run starting from /projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_f19_mg17_IC4PAMIP_20190816, which is an extension of the amip experiment carried out to provide restart and initial-condition files for the start date April 1st 2000.

**Comment by YanchunHe** [comment]
pdSST-piArcSIC NorESM2-LM is cmorized and ready to publish

**data path**

- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-piArcSIC

**version*
- v20190920

**other**
- PrePARE QC passed
- sha256sum updated

Please have a quick manual quality-check and confirm if it is OK to publish @lisesg

**Comment by lisesg** [comment]
Thanks Yanchun! I had a quick look at it, and it looks OK.

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-piArcSIC

**version**
- v20191108
(all the 100 members)

**sha256sum**
- .r*i1p1f1.sha256sum_v20191108b
( * include 1-100)

**Comment by monsieuralok** [comment]
@lisesg @YanchunHe published
