### ISSUE TITLE
[CMORization request] midHolocene - NorESM1-F

### ISSUE THREAD

**Issue by ChunchengGuo** [NorwegianClimateCentre/noresm2cmor#56]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS4659K/chuncheng/cases_fram/

**experiment_id**
midHolocene

**model_id**
NorESM1-F

**CASENAME(s) and years to be CMORized**
NBF1850OC_f19_tn11_01_6ka, 1501-1700

### Optional information
none

**parent_experiment_id**
no parent

**parent_experiment_rip**
r1i1p1

**parent_time_units**
no parent

**branch_method**
none

**other information**
note that the grid information is "tnx1v1"

**Comment by YanchunHe** [comment]
midHolocene NorESM1-F is cmorized and ready to publish

**data path**

- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM1-F/midHolocene/r1i1p1f1
version
-v20190920

**other**

- PrePARE QC passed
- sha256sum updated

Please have a quick manual quality-check and confirm if it is OK to publish @ChunchengGuo

**Comment by YanchunHe** [comment]
Confirmed and sent to publish

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
cmorized with additional fields

**datapath**
- /tos-project1/NS9034K/CMIP6/PMIP/NCC/NorESM1-F/midHolocene

**vesion**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@ChunchengGuo @YanchunHe published
