### ISSUE TITLE
[CMORization request] midPliocene-eoi400 - NorESM1-F

### ISSUE THREAD

**Issue by ChunchengGuo** [NorwegianClimateCentre/noresm2cmor#57]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS2345K/noresm/cases/PlioMIP2_rerun/

**experiment_id**
midPliocene-eoi400

**model_id**
NorESM1-F

**CASENAME(s) and years to be CMORized**
PlioMIP2_03, 2301-2500

### Optional information
none

**parent_experiment_id**
no parent

**parent_experiment_rip**
r1i1p1

**parent_time_units**
no parent

**branch_method**
none

**other information**
the ocean grid information (including grid, inicon, mertraoceans, secindex) is at (on Fram) - /cluster/shared/noresm/inputdata/ocn/micom/tnx1v1/PlioMIP2/
Let me know if any other input files are needed.

**Comment by ChunchengGuo** [comment]
@YanchunHe 
Four NorESM1-F Pliocene spedific ocean input files are here - /projects/NS9560K/cmor/griddata/tmp_pliocene

'section' and 'region' have been appended to the grid file.

just cp or mv these files to its parent directory if don't see any issues from them.

**Comment by YanchunHe** [comment]
midPliocene-eoi400 NorESM1-F is cmorized and ready to publish

**data path**

- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM1-F/midPliocene-eoi400/r1i1p1f1
version
-v20190920

**other**

- PrePARE QC passed
- sha256sum updated

Please have a quick manual quality-check and confirm if it is OK to publish @ChunchengGuo

**Comment by YanchunHe** [comment]
Confirmed and sent to publish

**Comment by monsieuralok** [comment]
@YanchunHe  midHolocene  midPliocene-eoi400 are part of CMIP or PMIP? as you mentioned data path 
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM1-F/midPliocene-eoi400/r1i1p1f1
version-v20190920

while it is 

/projects/NS9034K/CMIP6/PMIP/NCC/NorESM1-F/midPliocene-eoi400/r1i1p1f1
version-v20190920

**Comment by YanchunHe** [comment]
They are PMIP. I made the mistake in the path.
corrected above.

**Comment by monsieuralok** [comment]
midPliocene has only 1489 data sets while others have 2249. Is it OK with that? 
create CMIP6_PMIP_NCC_NorESM1-F_midPliocene-eoi400_r1i1p1f1_20191007.map 1489
create CMIP6_PMIP_NCC_NorESM1-F_lig127k_r1i1p1f1_20191007.map 2249
create CMIP6_PMIP_NCC_NorESM1-F_midHolocene_r1i1p1f1_20191007.map 2249

**Comment by ChunchengGuo** [comment]
yes @monsieuralok that is OK.

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
- /tos-project1/NS9034K/CMIP6/PMIP/NCC/NorESM1-F/midPliocene-eoi400

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@ChunchengGuo @YanchunHe published
