### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] add daily fields for NorESM2-LM - pdSST-futArcSIC  pdSST-pdSIC  pdSST-piArcSIC  piSST-pdSIC

### ISSUE THREAD

**Issue by YanchunHe** [NorwegianClimateCentre/noresm2cmor#59]
Include some more daily fields of tables AERday, Eday and CFday.

The following fields will be added:
zg10
zg500
wap500
ta500
ta850

data version will be named as: v20191009

Refer to Issue #28

**Comment by YanchunHe** [comment]
ta850 and zg850 are added in the cmorized output.
Ready to publish these additional fields to ESGF.

**data path**
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-futArcSIC/
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-pdSIC/
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-piArcSIC/
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/piSST-pdSIC/

Including all 100 realisations of data version v20191009

**data version**
- v20191009

**other information**
- PrePARE QC report updated
- sha256sum updated.

**Comment by monsieuralok** [comment]
@lisesg @YanchunHe published
