### ISSUE TITLE
Update CMIP6_Ofx table

### ISSUE THREAD

**Issue by YanchunHe** [NorwegianClimateCentre/noresm2cmor#61]
The Following fields are now supported:

Fields in  Ofx output (e.g., ocean grid files)
```
basin
sftof
thkcello
```

masscello is included in the monthly output.

**Sample output**
/scratch/yanchun/cmorout/NorESM2-LM/historical/v20190815/Ofx
- basin_Ofx_NorESM2-LM_historical_r1i1p1f1_gn.nc
- sftof_Ofx_NorESM2-LM_historical_r1i1p1f1_gn.nc
- thkcello_Ofx_NorESM2-LM_historical_r1i1p1f1_gr.nc
- volcello_Ofx_NorESM2-LM_historical_r1i1p1f1_gr.nc

**commit**
- 9a0c057128bc7cfd5d025ca2b4b9f9c2e78376eb

**Comment by YanchunHe** [comment]
in row 1442 of the CMIP6 google request sheet, the field 'masscello',
According to column F, it needs 'depth_bnds','pbot', which are available in the model output instead of 'grid info data'.
And also stated in the description (column L) " More generally, masscello is time dependent and reported as part of Omon".
It seems to me then it is more reasonable to include this 'masscello' in the Omon table instead of Ofx.

**Comment by YanchunHe** [comment]
## volcello

regarding volcello,

it is now in var_CMIP6_NorESM2_default.nml
```
‘volcello          ‘,’parea,pdepth  ','volcello                     ',
```
so that parea is fld, and pdepth is fld2 in m_modelsocn.F
```fortran
1232 c --- - Compute fixed cell volume of interpolated grid
1233         CASE ('volcello')
1234           DO j=1,jj
1235             DO i=1,ii
1236               DO k=ddm,1,-1
1237                 IF (fld(i,j,1).EQ.0.) THEN
1238                   fld(i,j,k)=1e20
1239                 ELSE
1240                   ptop=MIN(depth_bnds(1,k),fld(i,j,1))
1241                   pbot=MIN(depth_bnds(2,k),fld(i,j,1))
1242                   fld(i,j,k)=(pbot-ptop)*fld2(i,j,1)
1243                 ENDIF
1244               ENDDO
1245             ENDDO
1246           ENDDO
```
is this correct, @IngoBethke ? cos it looks to me, the 'fld' here in the program is 'parea' instead of 'depth'..

I also noticed 
fld and fld2 is swapped partially in special_post,
special_post, you swapped parea and pdepth (fld,fld2) in open_file,
```fortran
2423       IF (INDEX(special,'volcello').GT.0) THEN
2424         fld2=fld
2425         fld=0.
2426       ENDIF
```fortran

**Comment by IngoBethke** [comment]
The swapping is performed already during reading and not in special_post (if I am not mistaken). So pdepth should be fld in the computation of volcello. 

Concerning fx vs mon:
 
For our cmor-ized MICOM output, all fields interpolated to fixed levels have the grid id "gr" (r for regridded) while the uninterpolated layer output have the grid id "gn" (n for native). Fields like volcello and masscello are auxillary fields that are meant to be used for computations on physical/bgc fields. 

Naturally the "gn" versions of volcello and masscello should be time dependent (i.e. table Omon). 

However, I favor to keep the "gr" versions of volcello and masscello time-invarient (i.e. table Ofx). The time-variations of volume and mass of the regridded layers as a consequence of variation in bottom pressure/sea level are tiny and for most budget computations negligible. If we consider changing the gr versions of volcello and masscello to Omon then we probably should first assess a cost/benefit analysis. For backward compability, I'd prefer if you introduced a new volcello operator in keep the current one as it is (assuming that there is no bug). 

By the way, @matsbn has found that our vertical regridding implementation to fixed levels does not fully conform with the CMIP guidlines (I misinterpreted the guidelines when I initially try to  implement them). I cannot recall if @matsbn changed it in NorESM2 or not. Maybe he can comment on it.

**Comment by YanchunHe** [comment]
> The swapping is performed already during reading and not in special_post (if I am not mistaken). So pdepth should be fld in the computation of volcello.

OK, thanks! Yes, I was not accurate. My above-mentioned swapping was not in subroutine special_post, but during reading the fields (only use special_post as condition)

I see it is correct (but don't understand why swap in the code instead of specify the right order in the namelist)

> 
> Concerning fx vs mon:
> 
> For our cmor-ized MICOM output, all fields interpolated to fixed levels have the grid id "gr" (r for regridded) while the uninterpolated layer output have the grid id "gn" (n for native). Fields like volcello and masscello are auxillary fields that are meant to be used for computations on physical/bgc fields.
> 
> Naturally the "gn" versions of volcello and masscello should be time dependent (i.e. table Omon).
> 
> However, I favor to keep the "gr" versions of volcello and masscello time-invarient (i.e. table Ofx). The time-variations of volume and mass of the regridded layers as a consequence of variation in bottom pressure/sea level are tiny and for most budget computations negligible. If we consider changing the gr versions of volcello and masscello to Omon then we probably should first assess a cost/benefit analysis. For backward compability, I'd prefer if you introduced a new volcello operator in keep the current one as it is (assuming that there is no bug).
> 
> By the way, @matsbn has found that our vertical regridding implementation to fixed levels does not fully conform with the CMIP guidlines (I misinterpreted the guidelines when I initially try to implement them). I cannot recall if @matsbn changed it in NorESM2 or not. Maybe he can comment on it.

I will try to made another operator for volcello of Omon.

**Comment by IngoBethke** [comment]
The purpose of the four lines was not so much to "swap" parea and pdepth but rather to avoid that fld is set to the product of the two fields (because we need them separately in the computation of volcello).
