### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - CMIP6 PAMIP pdSST-futAntSIC name

### ISSUE THREAD

**Issue by lisesg** [NorwegianClimateCentre/noresm2cmor#67]
### Mandatory information:

**Mandatory information:**
Full path to the case(s) of the experiment on NIRD
Members 1-25:
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p8_pdSST-futAntSIC_mem1-25_f19_mg17_20191007
Members 26-50:
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p8_pdSST-futAntSIC_mem26-50_f19_mg17_20191007
Members 51-75:
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p8_pdSST-futAntSIC_mem51-75_f19_mg17_20191007
Members 76-100:
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p8_pdSST-futAntSIC_mem76-100_f19_mg17_20191007

**experiment_id**
pdSST-futAntSIC

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p8_pdSST-futAntSIC_mem1-25_f19_mg17_20191007: June 1st 2000 - May 31st 2001
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p8_pdSST-futAntSIC_mem26-50_f19_mg17_20191007: June 1st 2000 - May 31st 2001
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p8_pdSST-futAntSIC_mem51-75_f19_mg17_20191007: June 1st 2000 - May 31st 2001
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p8_pdSST-futAntSIC_mem76-100_f19_mg17_20191007: June 1st 2000 - May 31st 2001

**Optional information**
parent_experiment_id
amip

parent_experiment_rip
r1i1p1f1

parent_time_units
days since 1975-01-01 00:00:00

branch_method
'Hybrid-restart from year 2000-04-01 of amip',

other information
The experiment is a hybrid run starting from /projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_f19_mg17_IC4PAMIP_20190816, which is an extension of the amip experiment carried out to provide restart and initial-condition files for the start date April 1st 2000.

**Comment by YanchunHe** [comment]
Is the case name correct?

>Members 1-25:
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p7_pdSST-piAntSIC_mem1-25_f19_mg17_20191002

should be
>/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p8_pdSST-futAntSIC_mem1-25_f19_mg17_20191007

right?

**Comment by lisesg** [comment]
Yes, /projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p8_pdSST-futAntSIC_mem1-25_f19_mg17_20191007 is the correct path to the case. Sorry! I'll correct it above.

**Comment by YanchunHe** [comment]
CMORized and ready for publish

**data path**
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-futAntSIC

including 100 realisations in subfolders

**versions**
- v20190920
- v20191009

**other**
- sha256sum updated
- PrePARE QC passed

**Comment by monsieuralok** [comment]
@YanchunHe @lisesg published

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-futAntSIC

**version**
- v20191108
(all the 100 members)

**sha256sum**
- .r*i1p1f1.sha256sum_v20191108b
( * include 1-100)

**Comment by monsieuralok** [comment]
@YanchunHe @lisesg published
